USE [master]
GO

/****** Object:  Database [oktell_settings]    Script Date: 7/8/2021 8:23:13 AM ******/
CREATE DATABASE [oktell_settings]
 CONTAINMENT = NONE
 COLLATE Cyrillic_General_CI_AS

GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [oktell_settings].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [oktell_settings] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [oktell_settings] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [oktell_settings] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [oktell_settings] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [oktell_settings] SET ARITHABORT OFF 
GO

ALTER DATABASE [oktell_settings] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [oktell_settings] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [oktell_settings] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [oktell_settings] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [oktell_settings] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [oktell_settings] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [oktell_settings] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [oktell_settings] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [oktell_settings] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [oktell_settings] SET  DISABLE_BROKER 
GO

ALTER DATABASE [oktell_settings] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [oktell_settings] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [oktell_settings] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [oktell_settings] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [oktell_settings] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [oktell_settings] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [oktell_settings] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [oktell_settings] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [oktell_settings] SET  MULTI_USER 
GO

ALTER DATABASE [oktell_settings] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [oktell_settings] SET DB_CHAINING OFF 
GO

ALTER DATABASE [oktell_settings] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [oktell_settings] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [oktell_settings] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [oktell_settings] SET  READ_WRITE 
GO

